### ISSUE TITLE
Extension fails to install on Windows

### ISSUE THREAD

**Issue by ncaunt** [teddywing/chrome-copy-urls-from-all-tabs#2]
Hi,

When attempting to install version 0.3.0 of the extension on Windows (Chrome 57.0.2987.133) the following error is displayed:

`Package is invalid. Details: 'Invalid value for 'commands[1].default': MacCtrl+L.'.`

Version 0.2.0 works fine.

**Comment by teddywing** [comment]
Thanks for letting me know!

I'm afraid I don't have a Windows machine to test on. Would you be willing to test a possible fix? I can have a build ready within a day or so.

If you're interested in trying a fix, the problem should be here: https://github.com/teddywing/chrome-copy-urls-from-all-tabs/blob/91c43a2256d4622413fcf653c449dd4968e2818f/manifest.json#L36

**Comment by teddywing** [comment]
I've added a possible fix here: https://github.com/teddywing/chrome-copy-urls-from-all-tabs/commit/1ab43094f3308c880ab4aa81ae2b440d4bae44e9

Would you mind testing it out and letting me know if this fixes the error? You can either run this version (https://github.com/teddywing/chrome-copy-urls-from-all-tabs/archive/1ab43094f3308c880ab4aa81ae2b440d4bae44e9.zip) of the extension in developer mode (by following these instructions: https://developer.chrome.com/extensions/getstarted#unpacked), or install the bundled copy from here: https://snip.dssr.ch/?1e994722cd83c8bc#gGrvgiXb5CBjZGPydCPAHk0Ptjl+Bj9GUeL3iFpL6eE=

**Comment by teddywing** [comment]
It's been a while since I've heard from you. Assuming for now that the fix worked. I've applied the change in [v0.3.1](https://github.com/teddywing/chrome-copy-urls-from-all-tabs/releases/tag/v0.3.1):

https://github.com/teddywing/chrome-copy-urls-from-all-tabs/compare/91c43a2...3517fe8

If that doesn't fix the issue, feel free to re-open this or create a new issue.

Thanks again.
